### ISSUE TITLE
diff breaks when you use references

### ISSUE THREAD

**Issue by davidgoldelocks** [bump-sh/github-action#179]
https://github.com/bump-sh/github-action/pull/139 changed `diff` to use the two file input format
it does this by explicitly checking out the documentation file from the base branch into a tmp directory

however, this fails when your documentation file is not a single file e.g. when it uses local references

the git logic is only fetching the file you specify in the action config, so when `bump diff` tries to follow the references in the `tmp` directory it fails with `ENOENT: no such file or directory`

**Comment by paulRbr** [comment]
Hi @davidgoldelocks, thanks a lot for reporting this issue.

It's indeed problematic to restore only the root contract file. Let me get back to you as soon as we have a fix.

**Comment by paulRbr** [comment]
👋 @davidgoldelocks, 

I have released a fix and all future runs of the `bump-sh/github-action@v1` action should be working as you expect. Again thanks for reporting this issue and sorry for the unexpected behavior 💙.

**Comment by davidgoldelocks** [comment]
@paulRbr 
Thanks for the quick fix! Looks to be working again.

I assume that the single file idea was for efficiency purposes e.g. if you have a very large repo, you don't want to check it out twice. I personally don't have that problem, so it doesn't matter to me, but if you wanted to accommodate that use case you could take the directory to checkout as an optional explicit param.
