### ISSUE TITLE
Unexpected input(s) 'branch'

### ISSUE THREAD

**Issue by tbuteler** [bump-sh/github-action#275]
Using `bump-sh/github-action@v1` in a GitHub Action workflow, and while the documentation is successfully deployed, Bump seems to give me a warning:

> Warning: Unexpected input(s) 'branch', valid inputs are ['file', 'doc', 'token', 'command']

<img width="853" alt="Screenshot 2022-07-15 at 10 53 53" src="https://user-images.githubusercontent.com/330375/179200727-10aee86f-12b4-46d0-af37-baf8b3be7437.png">

Checking what GitHub is using and found this, which as far as I can tell is the latest version which should support `branch`, unless I'm mistaken:

> Download action repository 'bump-sh/github-action@v1' (SHA:7ee65a14f1236e0b53717df1668b188013c299e5)

Any help is appreciated, thank you!

---

Update: just had my CI run two steps that deployed versions of APIs to different branches on the same doc and I'm positive the `branch` input routed them appropriately, so it's likely just misguided warning?

**Comment by MPJHorner** [comment]
+1 I am also getting this error.
