### ISSUE TITLE
Unable to compute your documentation diff

### ISSUE THREAD

**Issue by calexander3** [bump-sh/github-action#299]
We have been using the GitHub action for a few weeks with no issues. How we are getting the following error consistently:

```
We were unable to compute your documentation diff. Sorry about that. Please try again later
```
Any way to get more information from this error?

**Comment by paulRbr** [comment]
Hi @calexander3, 

Sorry for the inconvenience. We have had some performance issues at Bump yesterday and you must have been affected by this.
Would you mind sending us both **previous** and **next** specification versions you were trying to diff please?

You can send both files to hello@bump.sh.

We will do our best to investigate and restore the feature as you have been using for the past few weeks!
Many thanks for your help and understanding 🙇‍♂️
Paul - from the Bump team

**Comment by calexander3** [comment]
Thanks @paulRbr! It looks like it starting working about 4 hours ago. The odd thing is that the cli continued to work even when the action was not.

**Comment by paulRbr** [comment]
> It looks like it starting working about 4 hours ago.

Hi @calexander3,

We have fixed an important performance bug last friday (16th september) so I'm happy to hear it helped to solve your issue. Thanks for your patience!
