### ISSUE TITLE
Unable to compute your documentation diff

### ISSUE THREAD

**Issue by calexander3** [bump-sh/github-action#479]
We have been seeing the following message starting on December 14th. Any way to get more information?

```We were unable to compute your documentation diff. Sorry about that. Please try again later```

**Comment by paulRbr** [comment]
Hi @calexander3, thanks for reporting this. Are you using the Github Action with authentication (with a Bump.sh account) or not? If so, could you please share your API documentation slug so we can investigate further?
We hope to be able to assist as soon as possible.

**Comment by calexander3** [comment]
It looks like it is just hitting the timeout period in the bump-cli. I'm going to close this issue and reopen it there. Thank you!

**Comment by calexander3** [comment]
For reference: https://github.com/bump-sh/cli/issues/555

**Comment by paulRbr** [comment]
Indeed, it's a limit of the CLI. Thanks for moving the issue there. I'll take a look at your provided files to investigate :bow:
